### ISSUE TITLE
Cannot run bin/magento

### ISSUE THREAD

**Issue by briscoda** [Magnetic/magento2-extension#1]
After installing the module, you cannot run bin/magento:

We're sorry, an error occurred. Try clearing the cache and code generation directories. By default, they are: var/cache, var/di, var/generation, and var/page_cache.

  [Zend\ServiceManager\Exception\ServiceNotCreatedException]  
  An abstract factory could not create an instance of magentosetupconsolecommandmoduleuninstallcommand(alias: Magento\Setup\Console\Command\ModuleUninstallCommand).  

  [Zend\ServiceManager\Exception\ServiceNotCreatedException]  
  An exception was raised while creating "Magento\Setup\Console\Command\ModuleUninstallCommand"; no instance returned  

  [Zend_Json_Exception]  
  Decoding failed: Syntax error

**Comment by mjgellada** [comment]
composer.json Line 17
`],`
to
`]`
